2025-05-19 15:28:21 [INFO] 백테스트 시작
2025-05-19 15:28:21 [INFO] 설정: Namespace(model_path='C:\\big19\\final_project\\v02_sac-trading\\models\\cnn_sac_model_20250519_143747', config_path=None, data_path=None, use_db=True, db_user='postgres', db_password='mysecretpassword', db_host='192.168.40.193', db_port=5432, db_name='mydb', symbol='tsla', results_dir='results/backtest', initial_balance=10000.0, transaction_fee_percent=0.0025, benchmark_data_path=None, window_size=None, override_window_size=False, feature_selection=None)
2025-05-19 15:28:21 [INFO] 설정을 성공적으로 로드했습니다.
2025-05-19 15:28:21 [INFO] 사용할 장치: cuda
2025-05-19 15:28:21 [INFO] 데이터베이스에서 데이터 로드 중...
2025-05-19 15:28:22 [INFO] 데이터베이스에서 tsla 데이터 로드 완료: 162694 행
2025-05-19 15:28:25 [INFO] 백테스트 실행 중...
2025-05-19 15:28:25 [ERROR] 백테스트 실행 중 오류 발생: 'trade_cost'
2025-05-19 15:28:25 [ERROR] Traceback (most recent call last):
  File "C:\big19\final_project\v02_sac-trading\src\backtesting\run_backtest.py", line 453, in main
    results = backtester.run_backtest(verbose=True)
  File "C:\big19\final_project\v02_sac-trading\src\backtesting\backtester.py", line 113, in run_backtest
    "cost": info["trade_cost"],
KeyError: 'trade_cost'

